### ISSUE TITLE
str-replace as a while loop

### ISSUE THREAD

**Issue by Snugug** [at-import/Sassy-Strings#4]
Don't remember why I wrote it this way instead of as a recursive function, but something to look at.

``` scss
@function str-replace($string, $search, $replace) {
  $length: str-length($replace);
  $index: str-index($string, $search);
  $slice: $string;
  @while $index != 0 {
    $slice: str-slice($slice, 0, $index - 1);
    $slice: $slice + $replace;
    $slice: $slice + str-slice($string, $index + $length);
    $index: str-index($slice, $search);
  }
  @return $slice;
}
```
