### ISSUE TITLE
[off-topic] sass interpolation in css comments

### ISSUE THREAD

**Issue by m5o** [at-import/Sassy-Strings#6]
Sorry guys for posting this question here. Maybe some sass pro had a solution for this.

Is it possible to pares css comments with sass and interpolate variables?

``` scss
$background-color: #FFF;

// comment dummy #{$background-color} interpolation
- or - 
/* comment dummy #{$background-color} interpolation */

result:
// comment dummy #FFF interpolation
```
